services:
  marketdb:
    image: postgres
    restart: always
    env_file: .env.yaml
    ports:
    - 5432:5432
    volumes:
      - ./marketdb/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 60s

  marketsvc:
    build:
      context: ./marketsvc
      dockerfile: Dockerfile
    volumes:
      - ./marketsvc:/code/
    env_file: .env.yaml
    ports:
    - 9090:9090
    command:
      - python3.12
      - server.py
    depends_on:
      marketdb:
        condition: service_healthy
